version: '2'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_NAME=test_db
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db
      - selenium
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "8888:8888"
      - "3000:3000"

  db:
    build:
      context: .
      dockerfile: local_db.Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data/
    shm_size: 1gb

  selenium:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - "4444:4444"
      - "5901:5901"

volumes:
  db-data:

