name: TesQA Pipeline

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Build and run Docker containers
        run: |
          docker-compose up -d --build
          docker-compose down
          docker-compose up -d
          docker exec -it web bash
        working-directory: tech-review-qacicd

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: tech-review-qacicd

      - name: Run Python Unit Tests
        run: |
          python manage.py makemigrations testapp
          python manage.py migrate
          python manage.py test
        working-directory: tech-review-qacicd

      - name: Run Selenium Tests
        run: |
          # Commands to run Selenium tests
        working-directory: tech-review-qacicd

  deploy:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'your-aws-region'

      - name: Deploy to AWS EKS and ECR
        run: |
          # Commands to deploy to AWS EKS and ECR
        working-directory: tech-review-qacicd

