name: My CI/CD Pipeline

on:
  push:
    branches:
      - main  # or any branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build application
        run: |
          # Add commands to build your application
          # For example:
          # npm install
          # npm run build

  test:
    runs-on: ubuntu-latest
    
    needs: build  # This ensures the 'test' job runs after the 'build' job
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run tests
        run: |
          # Add commands to run your tests
          # For example:
          # npm test

  deploy:
    runs-on: ubuntu-latest
    
    needs: test  # This ensures the 'deploy' job runs after the 'test' job
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Deploy application
        run: |
          # Add commands to deploy your application
          # For example:
          # npm run deploy

